<Target@Label>:
    font_size: 25
    size_hint: (.05, .03)
    color: 0, 0, 0, 1
    bcolor: .78, .92, .24, 1
    canvas.before:
        Color:
            rgba: self.bcolor
        Rectangle:
            pos: self.pos
            size: self.size

<Data@TextInput>:
    size_hint: (.05, .03)
    font_size: 25
    write_tab: False
    padding_y: -1

<TextBox@Label>:
    font_size: 25
    text_size: self.size
    halign: "left"
    valign: "bottom"